version: "3.8"

services:
  testdb:
    container_name: gardenruler-todo-testdb
    image: mariadb:10.6.2-focal
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: gardenruler
      MYSQL_DATABASE: test
      TZ: Asia/Seoul
    restart: always
    ports:
      - "3306:3306"
  apiserver:
    container_name: gardenruler-todo-apiserver
    build:
      context: .
      dockerfile: ./Dockerfile
    image: markruler/gardenruler-todo-apiserver:latest
    depends_on:
      - testdb
    restart: unless-stopped
    ports:
      - "8080:8080"
