spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: gardenruler
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
